name: Go
on: [pull_request,push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2

    - name: Check out
      uses: actions/checkout@v2

    - name: Building
      run: go build -v .

    - name: Testing
      run: go test -v ./...
